version: 2

models:
  - name: stg_customers
    description: Cleaned customer dataset.

    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

      - name: email
        tests:
          - not_null

  - name: stg_orders
    description: Cleaned orders dataset.

    columns:
      - name: order_id
        tests:
          - unique
          - not_null

      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id